import React, { createContext, useContext, useState } from "react";

const translations = {
  en: {
    dashboard: "Dashboard",
    products: "Products",
    orders: "Orders",
    users: "Users",
    categories: "Categories",
    activityLog: "Activity Log",
    addProduct: "Add Product",
    overview: "Overview",
    lastUpdated: "Last updated",
    refreshing: "Refreshing...",
    refresh: "Refresh",
    quickActions: "Quick Actions",
    recentOrders: "Recent Orders",
    unknown: "Unknown",
    paid: "Paid",
    pending: "Pending",
    noRecentOrders: "No recent orders",
    stockAlerts: "Stock Alerts",
    stock: "Stock",
    lowStock: "Low Stock",
    noStockAlerts: "No stock alerts",
    customerActivity: "Customer Activity",
    noRecentActivity: "No recent activity",
    // Overview/metrics
    totalSales: "Total Sales",
    totalOrders: "Total Orders",
    activeUsers: "Active Users",
    pendingOrders: "Pending Orders",
    lowStockMetric: "Low Stock",
    actionNeeded: "Action needed",
    recentRegistrations: "Recent Registrations",
    averageOrderValue: "Average Order Value",
    returnRate: "Return Rate",
    low: "Low",
    alerts: "Alerts",
    salesOverLast7Days: "Sales Over the Last 7 Days",
    dailySales: "Daily Sales",
    allGood: "All good",
    productsManagement: "Products Management",
    showAdvancedSearch: "Show Advanced Search",
    searchProducts: "Search products by name, description...",
    allCategories: "All Categories",
    image: "Image",
    name: "Name",
    category: "Category",
    price: "Price",
    actions: "Actions",
    itemsPerPage: "Items per page:",
    showing: "Showing",
    to: "to",
    of: "of",
    previous: "Previous",
    next: "Next",
    page: "Page",
    noProductsFound: "No products found.",
    edit: "Edit",
    delete: "Delete",
    ordersManagement: "Orders Management",
    searchByIdOrCustomer: "Search by ID or customer...",
    allStatuses: "All Statuses",
    orderId: "Order ID",
    customer: "Customer",
    date: "Date",
    total: "Total",
    paymentStatus: "Payment Status",
    shippingStatus: "Shipping Status",
    loading: "Loading...",
    noOrdersFound: "No orders found.",
    notPaid: "Not Paid",
    shipped: "Shipped",
    pendingShipment: "Pending Shipment",
    toggleShipped: "Order Shipped",
    newTopics: "NEW TOPICS",
    discoverProductsLudic: "Discover products with a ludic science touch.",
    shopNow: "Shop Now",
    whyShopWithUs: "Why Shop With Us?",
    funOriginalTshirts: "Fun, original, bright T-shirts with a genius vibe.",
    fastShipping: "Fast Shipping",
    uniqueDesigns: "Unique Designs",
    greatQuality: "Great Quality",
    product: "Product",
    descriptionHere: "Description goes here.",
    home: "Home",
    cart: "Cart",
    orderTracking: "Order Tracking",
    about: "About",
    faq: "FAQ",
    responsibility: "Responsibility",
    calendly: "Calendly",
    complaint: "Complaint",
    contactUsAt: "Contact us at",
    yourEmailAddress: "Your email address",
    subscribe: "Subscribe",
    newsletter: "Newsletter",
    usersManagement: "Users Management",
    searchByNameOrEmail: "Search by name or email...",
    allRoles: "All Roles",
    exportUsers: "Export Users",
    importUsers: "Import Users",
    noUsersFound: "No users found.",
    admin: "Admin",
    categoriesManagement: "Categories Management",
    searchCategories: "Search categories...",
    exportCategories: "Export Categories",
    importCategories: "Import Categories",
    addCategory: "Add Category",
    description: "Description",
    noCategoriesFound: "No categories found.",
    supportManagement: "Support Management",
    totalTickets: "Total Tickets",
    openTickets: "Open Tickets",
    resolvedTickets: "Resolved Tickets",
    avgResponseTime: "Avg Response Time",
    searchTickets: "Search Tickets",
    searchByCustomerSubject: "Search by customer, subject...",
    allPriorities: "All Priorities",
    inProgress: "In Progress",
    waitingCustomer: "Waiting Customer",
    resolved: "Resolved",
    closed: "Closed",
    priority: "Priority",
    subject: "Subject",
    ticket: "Ticket",
    age: "Age",
    view: "View",
    respond: "Respond",
    noSupportTickets: "No support tickets found",
    noTicketsMessage: "There are no support tickets matching your current filters.",
    status: "Status",
    refund: "Refund",
    shipping: "Shipping",
    billing: "Billing",
    general: "General",
    technical: "Technical",
    urgent: "Urgent",
    high: "High",
    medium: "Medium",
    today: "Today",
    orderNotReceived: "Order not received",
    refundRequest: "Refund request",
    technicalIssueWithLogin: "Technical issue with login",
    productQuestion: "Product question",
    billingError: "Billing error",
    newsletterManagement: "Newsletter Management",
    totalCampaigns: "Total Campaigns",
    totalRecipients: "Total Recipients",
    successRate: "Success Rate",
    last30Days: "Last 30 Days",
    sendNewsletter: "Send Newsletter",
    messageRichText: "Message (Rich Text)",
    sendImmediately: "Send Immediately",
    scheduleForLater: "Schedule for Later",
    scheduledNewsletters: "Scheduled Newsletters",
    scheduledFor: "Scheduled For",
    recipients: "Recipients",
    sentBy: "Sent By",
    dataManagement: "Data Management",
    productsDesc: "Product catalog with details, pricing, and inventory",
    ordersDesc: "Order history with customer and payment information",
    usersDesc: "Customer and admin user accounts",
    categoriesDesc: "Product category structure and hierarchy",
    newsletterSubscribers: "Newsletter Subscribers",
    newsletterSubscribersDesc: "Email newsletter subscription list",
    newsletterCampaigns: "Newsletter Campaigns",
    newsletterCampaignsDesc: "Newsletter campaign history and statistics",
    records: "records",
    logout: "Logout",
  },
  fr: {
    dashboard: "Tableau de bord",
    products: "Produits",
    orders: "Commandes",
    users: "Utilisateurs",
    categories: "Catégories",
    activityLog: "Journal d'activité",
    addProduct: "Ajouter un produit",
    overview: "Aperçu",
    lastUpdated: "Dernière mise à jour",
    refreshing: "Actualisation...",
    refresh: "Actualiser",
    quickActions: "Actions rapides",
    recentOrders: "Commandes récentes",
    unknown: "Inconnu",
    paid: "Payé",
    pending: "En attente",
    noRecentOrders: "Aucune commande récente",
    stockAlerts: "Alertes de stock",
    stock: "Stock",
    lowStock: "Stock faible",
    noStockAlerts: "Aucune alerte de stock",
    customerActivity: "Activité client",
    noRecentActivity: "Aucune activité récente",
    // Overview/metrics
    totalSales: "Ventes totales",
    totalOrders: "Commandes totales",
    activeUsers: "Utilisateurs actifs",
    pendingOrders: "Commandes en attente",
    lowStockMetric: "Stock faible",
    actionNeeded: "Action requise",
    recentRegistrations: "Inscriptions récentes",
    averageOrderValue: "Valeur moyenne des commandes",
    returnRate: "Taux de retour",
    low: "Faible",
    alerts: "Alertes",
    salesOverLast7Days: "Ventes sur les 7 derniers jours",
    dailySales: "Ventes quotidiennes",
    allGood: "Tout est bon",
    productsManagement: "Gestion des produits",
    showAdvancedSearch: "Recherche avancée",
    searchProducts: "Rechercher des produits par nom, description...",
    allCategories: "Toutes les catégories",
    image: "Image",
    name: "Nom",
    category: "Catégorie",
    price: "Prix",
    actions: "Actions",
    itemsPerPage: "Articles par page :",
    showing: "Affichage",
    to: "à",
    of: "de",
    previous: "Précédent",
    next: "Suivant",
    page: "Page",
    noProductsFound: "Aucun produit trouvé.",
    edit: "Éditer",
    delete: "Supprimer",
    ordersManagement: "Gestion des commandes",
    searchByIdOrCustomer: "Rechercher par ID ou client...",
    allStatuses: "Tous les statuts",
    orderId: "ID de commande",
    customer: "Client",
    date: "Date",
    total: "Total",
    paymentStatus: "Statut de paiement",
    shippingStatus: "Statut de livraison",
    loading: "Chargement...",
    noOrdersFound: "Aucune commande trouvée.",
    notPaid: "Non payé",
    shipped: "Livré",
    pendingShipment: "En attente de livraison",
    toggleShipped: "Commande livrée",
    newTopics: "NOUVEAUX SUJETS",
    discoverProductsLudic: "Découvrez des produits avec une touche ludique scientifique.",
    shopNow: "Acheter maintenant",
    whyShopWithUs: "Pourquoi acheter chez nous ?",
    funOriginalTshirts: "T-shirts amusants, originaux et lumineux avec une touche de génie.",
    fastShipping: "Livraison rapide",
    uniqueDesigns: "Designs uniques",
    greatQuality: "Grande qualité",
    product: "Produit",
    descriptionHere: "La description va ici.",
    home: "Accueil",
    cart: "Panier",
    orderTracking: "Suivi de commande",
    about: "À propos",
    faq: "FAQ",
    responsibility: "Responsabilité",
    calendly: "Calendly",
    complaint: "Plainte",
    contactUsAt: "Contactez-nous à",
    yourEmailAddress: "Votre adresse e-mail",
    subscribe: "S'abonner",
    newsletter: "Newsletter",
    usersManagement: "Gestion des utilisateurs",
    searchByNameOrEmail: "Rechercher par nom ou e-mail...",
    allRoles: "Tous les rôles",
    exportUsers: "Exporter les utilisateurs",
    importUsers: "Importer les utilisateurs",
    noUsersFound: "Aucun utilisateur trouvé.",
    admin: "Admin",
    categoriesManagement: "Gestion des catégories",
    searchCategories: "Rechercher des catégories...",
    exportCategories: "Exporter les catégories",
    importCategories: "Importer les catégories",
    addCategory: "Ajouter une catégorie",
    description: "Description",
    noCategoriesFound: "Aucune catégorie trouvée.",
    supportManagement: "Gestion du support",
    totalTickets: "Nombre total de tickets",
    openTickets: "Tickets ouverts",
    resolvedTickets: "Tickets résolus",
    avgResponseTime: "Temps de réponse moyen",
    searchTickets: "Rechercher des tickets",
    searchByCustomerSubject: "Rechercher par client, sujet...",
    allPriorities: "Toutes les priorités",
    inProgress: "En cours",
    waitingCustomer: "En attente du client",
    resolved: "Résolu",
    closed: "Fermé",
    priority: "Priorité",
    subject: "Sujet",
    ticket: "Ticket",
    age: "Âge",
    view: "Voir",
    respond: "Répondre",
    noSupportTickets: "Aucun ticket de support trouvé",
    noTicketsMessage: "Aucun ticket de support ne correspond à vos filtres actuels.",
    status: "Statut",
    refund: "Remboursement",
    shipping: "Livraison",
    billing: "Facturation",
    general: "Général",
    technical: "Technique",
    urgent: "Urgent",
    high: "Haute",
    medium: "Moyenne",
    today: "Aujourd'hui",
    orderNotReceived: "Commande non reçue",
    refundRequest: "Demande de remboursement",
    technicalIssueWithLogin: "Problème technique avec la connexion",
    productQuestion: "Question sur le produit",
    billingError: "Erreur de facturation",
    newsletterManagement: "Gestion de la newsletter",
    totalCampaigns: "Nombre total de campagnes",
    totalRecipients: "Nombre total de destinataires",
    successRate: "Taux de réussite",
    last30Days: "30 derniers jours",
    sendNewsletter: "Envoyer la newsletter",
    messageRichText: "Message (texte enrichi)",
    sendImmediately: "Envoyer immédiatement",
    scheduleForLater: "Planifier pour plus tard",
    scheduledNewsletters: "Newsletters programmées",
    scheduledFor: "Programmé pour",
    recipients: "Destinataires",
    sentBy: "Envoyé par",
    dataManagement: "Gestion des données",
    productsDesc: "Catalogue de produits avec détails, prix et inventaire",
    ordersDesc: "Historique des commandes avec informations client et paiement",
    usersDesc: "Comptes utilisateur et administrateur",
    categoriesDesc: "Structure et hiérarchie des catégories de produits",
    newsletterSubscribers: "Abonnés à la newsletter",
    newsletterSubscribersDesc: "Liste d'abonnement à la newsletter par e-mail",
    newsletterCampaigns: "Campagnes de newsletter",
    newsletterCampaignsDesc: "Historique des campagnes de newsletter et statistiques",
    records: "enregistrements",
    logout: "Déconnexion",
  },
};

const LangContext = createContext();

export const useLang = () => useContext(LangContext);

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState("en");
  const t = (key) => translations[lang][key] || key;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}; 